package schedule

import "errors"

var (
	ErrNotFound          = errors.New("scheduled task not found")
	ErrInvalidID         = errors.New("invalid scheduled task id")
	ErrNameRequired      = errors.New("scheduled task name is required")
	ErrPromptRequired    = errors.New("scheduled task prompt is required")
	ErrPromptTooLarge    = errors.New("scheduled task prompt is too large")
	ErrOwnerRequired     = errors.New("scheduled task owner is required")
	ErrInvalidKind       = errors.New("scheduled task kind must be once or cron")
	ErrInvalidTime       = errors.New("scheduled task time must be in the future")
	ErrInvalidCron       = errors.New("invalid five-field cron expression")
	ErrInvalidTimezone   = errors.New("invalid IANA timezone")
	ErrInvalidMaxRuns    = errors.New("max runs cannot be negative")
	ErrInvalidOverlap    = errors.New("invalid overlap policy")
	ErrChatNotFound      = errors.New("scheduled task chat not found")
	ErrProjectRequired   = errors.New("scheduled tasks require a project chat")
	ErrProjectMismatch   = errors.New("scheduled task project does not match its chat")
	ErrAccessDenied      = errors.New("scheduled task access denied")
	ErrOwnerUnregistered = errors.New("scheduled task owner is no longer registered")
	ErrAlreadyExists     = errors.New("scheduled task already exists")
	ErrExecutorBusy      = errors.New("scheduled task chat is busy")
	ErrTaskDisabled      = errors.New("scheduled task is disabled")
	ErrMaxRunsReached    = errors.New("scheduled task has reached its maximum runs")
	ErrIntervalTooSmall  = errors.New("cron schedule fires more often than the minimum interval")
	ErrProjectQuota      = errors.New("project has reached its scheduled task limit")
	ErrArmRequiresUser   = errors.New("arming a scheduled task requires a user")

	ErrRunNotFound         = errors.New("scheduled run not found")
	ErrChainCycle          = errors.New("scheduled task chain contains a cycle")
	ErrChainTooDeep        = errors.New("scheduled task chain is too deep")
	ErrChainTooManyLinks   = errors.New("scheduled task has too many chained tasks")
	ErrChainTargetNotFound = errors.New("chained scheduled task not found")
	ErrChainCrossProject   = errors.New("chained scheduled task belongs to another project")
	ErrInvalidChainWhen    = errors.New("chain condition must be success, failure, or always")
	ErrInvalidChainDelay   = errors.New("chain delay must be between 0 and 10080 minutes")

	ErrGateInvalidKind      = errors.New("unknown scheduled task condition kind")
	ErrGatePatternRequired  = errors.New("outputContains condition requires a pattern")
	ErrGateInvalidPattern   = errors.New("outputContains pattern is not a valid regular expression")
	ErrGateInvalidReference = errors.New("outputContains inLastRunOf must be self or a task id")
	ErrGateInvalidURL       = errors.New("httpStatus condition requires an http or https url")
	ErrGateInvalidExpect    = errors.New("condition expect value is out of range")
	ErrGateCommandRequired  = errors.New("commandExitCode condition requires a command")
	ErrGateWeekdaysRequired = errors.New("weekdays condition requires days between 0 and 6")
	ErrGateInvalidMinutes   = errors.New("notIfRanWithin condition requires a positive minute window")
)
