package project

// Secrets are mirrored to <project.Cwd>/.env so dotenv-aware tools (Python
// python-dotenv, Node dotenv, shell `set -a; source .env`, etc.) running
// inside the container see them too. The container's `claude` process gets
// them via `--env` separately — this file is the convenience copy for any
// scripts the agent runs.
//
// Ownership: the file is chowned to the host uid that maps to root inside
// the unprivileged container's idmap (LXD default = 1000000). Mode 0600.

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// containerRootHostUID is the host uid that LXD's default idmap presents as
// root inside the unprivileged container. Duplicated from the containers
// package — they must stay in lockstep.
const containerRootHostUID = 1000000

const envFileName = ".env"

const envHeader = "# Generated by remote.futrx — managed via project Secrets UI.\n" +
	"# Edits here will be overwritten on the next secret change.\n"

func (s *secretStore) syncEnvFile(ctx context.Context, id ID, cwd string) error {
	if cwd == "" || s.repo == nil {
		return nil
	}
	secrets, err := s.repo.List(ctx, id)
	if err != nil {
		return fmt.Errorf("list secrets: %w", err)
	}
	return writeEnvFile(cwd, secrets)
}

func writeEnvFile(cwd string, secrets []Secret) error {
	path := filepath.Join(cwd, envFileName)
	if len(secrets) == 0 {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove .env: %w", err)
		}
		return nil
	}

	var buf strings.Builder
	buf.WriteString(envHeader)
	for _, sec := range secrets {
		buf.WriteString(sec.Key)
		buf.WriteByte('=')
		buf.WriteString(escapeEnvValue(sec.Value))
		buf.WriteByte('\n')
	}

	// Atomic write: temp file in the same dir, then rename.
	tmp, err := os.CreateTemp(cwd, ".env-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp .env: %w", err)
	}
	defer os.Remove(tmp.Name())
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return fmt.Errorf("chmod temp .env: %w", err)
	}
	if _, err := tmp.WriteString(buf.String()); err != nil {
		tmp.Close()
		return fmt.Errorf("write temp .env: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp .env: %w", err)
	}
	// Chown to the container's mapped root uid BEFORE rename so the
	// container sees correct ownership the instant the file appears.
	if err := os.Chown(tmp.Name(), containerRootHostUID, containerRootHostUID); err != nil {
		return fmt.Errorf("chown temp .env: %w", err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return fmt.Errorf("rename .env: %w", err)
	}
	return nil
}

// escapeEnvValue produces a double-quoted .env value with conservative
// escaping: backslash and double-quote get backslash-escaped; \n and \r
// become literal \n / \r escape sequences (most dotenv libs decode them).
func escapeEnvValue(v string) string {
	var b strings.Builder
	b.Grow(len(v) + 2)
	b.WriteByte('"')
	for _, r := range v {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
