// Package auxmodel is the platform's *auxiliary* text model: a small, cheap
// model — a local Ollama build, or any OpenAI-compatible endpoint — that does
// the platform's own little text chores.
//
// It is emphatically not a coding agent and never replaces one. The jobs it
// takes are the ones the platform today either does crudely (a chat title is
// the first sixty characters of the first prompt) or pays agent tokens for.
// Every one of those jobs must keep working when this service is switched
// off, unreachable, or slow: callers ask, and fall back to exactly what they
// did before if the answer does not arrive. Nothing here may block or fail a
// user action.
package auxmodel

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"strings"
)

// ErrInvalidConfig is returned for configurations the operator can fix. It is
// the only validation error the handler maps to 400.
var ErrInvalidConfig = errors.New("invalid auxiliary model settings")

// The two provider shapes this service speaks. They differ only in the path
// they post to and the JSON they exchange; everything above them is shared.
const (
	// ProviderOllama posts to {baseUrl}/api/chat. It is the default because
	// the intended deployment is an Ollama daemon on this same host, bound to
	// loopback, with no key at all.
	ProviderOllama = "ollama"
	// ProviderOpenAICompatible posts to {baseUrl}/v1/chat/completions, with a
	// bearer token when one is stored. It covers OpenAI itself, Groq,
	// Together, llama.cpp's server, vLLM, LM Studio, and anything else that
	// implements that route.
	ProviderOpenAICompatible = "openai-compatible"
)

// Defaults. A fresh install already describes a working local Ollama, so
// enabling the service is a one-switch decision for the intended setup.
const (
	DefaultOllamaBaseURL  = "http://127.0.0.1:11434"
	DefaultModel          = "qwen2.5:3b"
	DefaultTimeoutSeconds = 30
	// DefaultMaxTokens is the operator's ceiling on one answer, and it equals
	// the largest per-job cap on purpose: the real limiting is done by the
	// per-job caps below (a title gets 40 tokens whatever this says), so the
	// default should not be the thing that truncates the one job — a client
	// message translation — that genuinely needs room.
	DefaultMaxTokens = 1200
)

// Bounds on the two numeric fields. The timeout ceiling matters most: this is
// a nice-to-have running behind user actions, and a two-minute wait for a
// chat title is not a feature.
const (
	MinTimeoutSeconds = 3
	MaxTimeoutSeconds = 120
	MinMaxTokens      = 16
	MaxMaxTokens      = 4096
)

// Job names one of the platform chores this model may take. Each is
// individually toggleable, and every one of them has a fallback.
type Job string

const (
	// JobChatTitle replaces "first 60 characters of the first prompt" with a
	// 3–6 word title in the language the person actually wrote in.
	JobChatTitle Job = "chatTitle"
	// JobRunSummary turns the raw tail of an assistant message into the one
	// sentence a Telegram or WhatsApp notification should carry.
	JobRunSummary Job = "runSummary"
	// JobCommitMessage turns `git diff --stat` plus the changed file names
	// into a conventional-commit subject. File *contents* are never read.
	JobCommitMessage Job = "commitMessage"
	// JobTranslate powers the "Translate to Arabic/English" button on a
	// client message template.
	JobTranslate Job = "translate"
	// JobChatSummary stores a one-line summary on chat meta after a run
	// settles, which the sidebar and the dashboard show as a subtitle.
	JobChatSummary Job = "chatSummary"
)

// Jobs lists every job in the order the settings panel renders them.
func Jobs() []Job {
	return []Job{JobChatTitle, JobRunSummary, JobCommitMessage, JobTranslate, JobChatSummary}
}

// JobLabel is the human name of a job, so the panel and this package cannot
// disagree about what a toggle is called.
func JobLabel(job Job) string {
	switch job {
	case JobChatTitle:
		return "Chat titles"
	case JobRunSummary:
		return "Notification summaries"
	case JobCommitMessage:
		return "Commit messages"
	case JobTranslate:
		return "Client message translation"
	case JobChatSummary:
		return "Chat summaries"
	default:
		return string(job)
	}
}

// maxOutputTokens is the per-job ceiling on the answer, applied on top of the
// operator's own MaxTokens. A title that costs 256 tokens to produce is a
// title generated by a runaway model, and capping it here is cheaper than
// trimming the result afterwards.
func maxOutputTokens(job Job) int {
	switch job {
	case JobChatTitle:
		return 40
	case JobCommitMessage:
		return 60
	case JobRunSummary, JobChatSummary:
		return 160
	case JobTranslate:
		return 1200
	default:
		return DefaultMaxTokens
	}
}

// JobSource is where one job's text comes from. It replaced a plain on/off
// toggle when the free-tier provider pool arrived: "off" is still off, and
// what used to be "on" is now the explicit choice between the operator's own
// endpoint and the pool.
type JobSource string

const (
	// SourceLocal sends the job to the endpoint configured below — the local
	// Ollama on this host, or whatever OpenAI-compatible URL replaced it.
	SourceLocal JobSource = "local"
	// SourcePool sends the job through the free-tier provider pool, which
	// picks a provider and fails over between them invisibly. A pool that
	// cannot answer falls back to the local endpoint, and a local endpoint
	// that cannot answer falls back to the job's original non-AI behaviour.
	SourcePool JobSource = "pool"
	// SourceOff restores exactly what the platform did before this feature
	// existed.
	SourceOff JobSource = "off"
)

// JobSources lists every source in the order the settings panel offers them.
func JobSources() []JobSource { return []JobSource{SourceLocal, SourcePool, SourceOff} }

// NormalizeSource maps anything a client sends onto a known source.
// Unrecognized input becomes the local endpoint rather than the pool: a typo
// must never silently start spending somebody's free tier.
func NormalizeSource(source string) JobSource {
	switch JobSource(strings.ToLower(strings.TrimSpace(source))) {
	case SourcePool:
		return SourcePool
	case SourceOff:
		return SourceOff
	default:
		return SourceLocal
	}
}

// JobSettings is the per-job source map. A job that is absent from the
// document runs locally: the toggles default to on once the service itself
// is enabled, and a document written before a job existed must not silently
// switch that job off for everybody.
type JobSettings map[Job]JobSource

// UnmarshalJSON accepts both shapes this document has had: the booleans
// written before per-job sources existed, and the source strings written
// since. A stored `true` becomes SourceLocal, which is exactly what it meant.
func (s *JobSettings) UnmarshalJSON(data []byte) error {
	var raw map[Job]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	out := make(JobSettings, len(raw))
	for job, value := range raw {
		var source string
		if err := json.Unmarshal(value, &source); err == nil {
			out[job] = NormalizeSource(source)
			continue
		}
		var enabled bool
		if err := json.Unmarshal(value, &enabled); err != nil {
			// A value in neither shape is a corrupt document, not a reason to
			// refuse to boot: the job falls back to running locally.
			out[job] = SourceLocal
			continue
		}
		if enabled {
			out[job] = SourceLocal
		} else {
			out[job] = SourceOff
		}
	}
	*s = out
	return nil
}

// DefaultJobSettings points every known job at the local endpoint.
func DefaultJobSettings() JobSettings {
	settings := make(JobSettings, len(Jobs()))
	for _, job := range Jobs() {
		settings[job] = SourceLocal
	}
	return settings
}

// Normalize drops unknown job names and fills in the ones the document never
// mentioned, so every reader below this point sees a complete map.
func (s JobSettings) Normalize() JobSettings {
	out := make(JobSettings, len(Jobs()))
	for _, job := range Jobs() {
		source, found := s[job]
		if !found {
			out[job] = SourceLocal
			continue
		}
		out[job] = NormalizeSource(string(source))
	}
	return out
}

// Source reports where one job's text should come from. An unknown job is
// always off: a caller that invents a name gets the fallback, not a model.
func (s JobSettings) Source(job Job) JobSource {
	source, found := s.Normalize()[job]
	if !found {
		return SourceOff
	}
	return source
}

// Enabled reports whether one job may run at all, by either route.
func (s JobSettings) Enabled(job Job) bool {
	return s.Source(job) != SourceOff
}

// Config is the auxiliary model configuration persisted at
// DATA_DIR/aux-model.json. The file is mode 0600 because APIKey is a bearer
// credential for whatever endpoint BaseURL names.
type Config struct {
	Enabled  bool   `json:"enabled"`
	Provider string `json:"provider"`
	BaseURL  string `json:"baseUrl"`
	Model    string `json:"model"`
	// APIKey is optional. A loopback Ollama needs none; a hosted
	// OpenAI-compatible endpoint needs one.
	APIKey         string      `json:"apiKey,omitempty"`
	TimeoutSeconds int         `json:"timeoutSeconds"`
	MaxTokens      int         `json:"maxTokens"`
	Jobs           JobSettings `json:"jobs,omitempty"`
	UpdatedAt      int64       `json:"updatedAt,omitempty"`
}

// DefaultConfig is what a server starts with: off, but already describing the
// local Ollama the docs tell an operator to install.
func DefaultConfig() Config {
	return Config{
		Enabled:        false,
		Provider:       ProviderOllama,
		BaseURL:        DefaultOllamaBaseURL,
		Model:          DefaultModel,
		TimeoutSeconds: DefaultTimeoutSeconds,
		MaxTokens:      DefaultMaxTokens,
		Jobs:           DefaultJobSettings(),
	}
}

// Normalize trims operator-entered values, clamps the numbers, and fills
// fields a document written by an older build may be missing.
func (c Config) Normalize() Config {
	c.Provider = strings.ToLower(strings.TrimSpace(c.Provider))
	if c.Provider != ProviderOpenAICompatible {
		c.Provider = ProviderOllama
	}
	c.BaseURL = strings.TrimRight(strings.TrimSpace(c.BaseURL), "/")
	if c.BaseURL == "" && c.Provider == ProviderOllama {
		c.BaseURL = DefaultOllamaBaseURL
	}
	c.Model = strings.TrimSpace(c.Model)
	if c.Model == "" && c.Provider == ProviderOllama {
		c.Model = DefaultModel
	}
	c.APIKey = strings.TrimSpace(c.APIKey)
	switch {
	case c.TimeoutSeconds <= 0:
		c.TimeoutSeconds = DefaultTimeoutSeconds
	case c.TimeoutSeconds < MinTimeoutSeconds:
		c.TimeoutSeconds = MinTimeoutSeconds
	case c.TimeoutSeconds > MaxTimeoutSeconds:
		c.TimeoutSeconds = MaxTimeoutSeconds
	}
	switch {
	case c.MaxTokens <= 0:
		c.MaxTokens = DefaultMaxTokens
	case c.MaxTokens < MinMaxTokens:
		c.MaxTokens = MinMaxTokens
	case c.MaxTokens > MaxMaxTokens:
		c.MaxTokens = MaxMaxTokens
	}
	c.Jobs = c.Jobs.Normalize()
	return c
}

// Configured reports whether the service has an endpoint and a model to call.
func (c Config) Configured() bool {
	normalized := c.Normalize()
	return normalized.BaseURL != "" && normalized.Model != ""
}

// Active reports whether a caller may reach the model at all.
func (c Config) Active() bool {
	return c.Enabled && c.Configured()
}

// PublicConfig is the admin-facing view. The key is never echoed back: the
// caller sees only whether one is stored and its masked tail.
type PublicConfig struct {
	Enabled        bool   `json:"enabled"`
	Configured     bool   `json:"configured"`
	Provider       string `json:"provider"`
	BaseURL        string `json:"baseUrl"`
	Model          string `json:"model"`
	APIKeyMasked   string `json:"apiKeyMasked,omitempty"`
	KeyConfigured  bool   `json:"keyConfigured"`
	TimeoutSeconds int    `json:"timeoutSeconds"`
	MaxTokens      int    `json:"maxTokens"`
	// Jobs maps each job id onto its source: "local", "pool", or "off".
	Jobs      map[string]string `json:"jobs"`
	JobLabels []JobDescriptor   `json:"jobLabels"`
	Providers []string          `json:"providers"`
	// Sources echoes the vocabulary of the Jobs map so the panel never
	// hard-codes a second copy of it.
	Sources []string `json:"sources"`
	// PoolAvailable reports whether the free-tier provider pool could take a
	// job right now. The panel uses it to warn that a job set to "pool" would
	// currently fall back to the local endpoint.
	PoolAvailable bool     `json:"poolAvailable"`
	Defaults      Defaults `json:"defaults"`
	UpdatedAt     int64    `json:"updatedAt,omitempty"`
}

// JobDescriptor names one toggle for the settings panel, so the label lives
// in one place rather than in both the panel and this package.
type JobDescriptor struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

// Defaults are the values the panel pre-fills and the bounds it validates
// against, echoed so the browser never hard-codes a second copy of them.
type Defaults struct {
	OllamaBaseURL     string `json:"ollamaBaseUrl"`
	Model             string `json:"model"`
	TimeoutSeconds    int    `json:"timeoutSeconds"`
	MaxTokens         int    `json:"maxTokens"`
	MinTimeoutSeconds int    `json:"minTimeoutSeconds"`
	MaxTimeoutSeconds int    `json:"maxTimeoutSeconds"`
	MinMaxTokens      int    `json:"minMaxTokens"`
	MaxMaxTokens      int    `json:"maxMaxTokens"`
}

// Public renders the admin-facing view of a configuration.
func (c Config) Public() PublicConfig {
	c = c.Normalize()
	jobs := make(map[string]string, len(c.Jobs))
	labels := make([]JobDescriptor, 0, len(Jobs()))
	for _, job := range Jobs() {
		jobs[string(job)] = string(c.Jobs.Source(job))
		labels = append(labels, JobDescriptor{ID: string(job), Label: JobLabel(job)})
	}
	sources := make([]string, 0, len(JobSources()))
	for _, source := range JobSources() {
		sources = append(sources, string(source))
	}
	return PublicConfig{
		Enabled:        c.Enabled,
		Configured:     c.Configured(),
		Provider:       c.Provider,
		BaseURL:        c.BaseURL,
		Model:          c.Model,
		APIKeyMasked:   MaskSecret(c.APIKey),
		KeyConfigured:  c.APIKey != "",
		TimeoutSeconds: c.TimeoutSeconds,
		MaxTokens:      c.MaxTokens,
		Jobs:           jobs,
		JobLabels:      labels,
		Providers:      []string{ProviderOllama, ProviderOpenAICompatible},
		Sources:        sources,
		Defaults: Defaults{
			OllamaBaseURL:     DefaultOllamaBaseURL,
			Model:             DefaultModel,
			TimeoutSeconds:    DefaultTimeoutSeconds,
			MaxTokens:         DefaultMaxTokens,
			MinTimeoutSeconds: MinTimeoutSeconds,
			MaxTimeoutSeconds: MaxTimeoutSeconds,
			MinMaxTokens:      MinMaxTokens,
			MaxMaxTokens:      MaxMaxTokens,
		},
		UpdatedAt: c.UpdatedAt,
	}
}

// ClientConfig is what every signed-in user may read: whether a given job may
// be offered in the UI at all. It carries no endpoint, no model name, and no
// key — a member does not need to know which box answers.
type ClientConfig struct {
	Enabled bool            `json:"enabled"`
	Jobs    map[string]bool `json:"jobs"`
}

// Client renders the member-facing view for a deployment with no provider
// pool: a job is available only when the local endpoint could serve it.
func (c Config) Client() ClientConfig {
	return c.ClientWithPool(false)
}

// ClientWithPool renders the member-facing view. A job is reported available
// only when the route it is set to could actually answer, so a button is
// never shown for something that would immediately fall back:
//
//   - "off" is never available;
//   - "local" needs the service switched on and an endpoint configured;
//   - "pool" needs either the pool to be ready or the local endpoint to be
//     configured, because a pool job falls back to local before it gives up.
func (c Config) ClientWithPool(poolAvailable bool) ClientConfig {
	c = c.Normalize()
	jobs := make(map[string]bool, len(Jobs()))
	anyAvailable := false
	for _, job := range Jobs() {
		available := c.Enabled
		switch c.Jobs.Source(job) {
		case SourceOff:
			available = false
		case SourcePool:
			available = available && (poolAvailable || c.Configured())
		default:
			available = available && c.Configured()
		}
		jobs[string(job)] = available
		anyAvailable = anyAvailable || available
	}
	return ClientConfig{Enabled: anyAvailable, Jobs: jobs}
}

const maskPrefix = "••••"

// MaskSecret renders a stored secret as the mask prefix plus its last four
// characters: enough for an operator to recognize which credential is
// installed, never enough to reuse it.
func MaskSecret(secret string) string {
	secret = strings.TrimSpace(secret)
	if secret == "" {
		return ""
	}
	runes := []rune(secret)
	if len(runes) <= 4 {
		return maskPrefix
	}
	return maskPrefix + string(runes[len(runes)-4:])
}

// UpdateInput is the admin PUT body. The key follows the same write-only
// semantics as every other stored credential here: an empty string keeps what
// is stored (the client only ever saw a mask), and ClearAPIKey removes it.
//
// Jobs is a partial map on purpose: a client may flip one toggle without
// restating the other four.
type UpdateInput struct {
	Enabled        bool   `json:"enabled"`
	Provider       string `json:"provider"`
	BaseURL        string `json:"baseUrl"`
	Model          string `json:"model"`
	APIKey         string `json:"apiKey"`
	ClearAPIKey    bool   `json:"clearApiKey"`
	TimeoutSeconds int    `json:"timeoutSeconds"`
	MaxTokens      int    `json:"maxTokens"`
	// Jobs maps a job id onto "local", "pool" or "off". It is partial on
	// purpose: a client may change one job's route without restating the
	// other four.
	Jobs map[string]string `json:"jobs"`
}

// Apply folds an update onto the stored configuration, preserving the key the
// caller did not resubmit.
func (c Config) Apply(input UpdateInput) Config {
	next := c.Normalize()
	next.Enabled = input.Enabled
	if provider := strings.ToLower(strings.TrimSpace(input.Provider)); provider != "" {
		next.Provider = provider
	}
	if baseURL := strings.TrimSpace(input.BaseURL); baseURL != "" {
		next.BaseURL = baseURL
	}
	if model := strings.TrimSpace(input.Model); model != "" {
		next.Model = model
	}
	if input.TimeoutSeconds > 0 {
		next.TimeoutSeconds = input.TimeoutSeconds
	}
	if input.MaxTokens > 0 {
		next.MaxTokens = input.MaxTokens
	}
	switch {
	case input.ClearAPIKey:
		next.APIKey = ""
	case strings.TrimSpace(input.APIKey) != "":
		next.APIKey = strings.TrimSpace(input.APIKey)
	}
	if len(input.Jobs) > 0 {
		jobs := next.Jobs.Normalize()
		for name, source := range input.Jobs {
			job := Job(strings.TrimSpace(name))
			if _, known := jobs[job]; known {
				jobs[job] = NormalizeSource(source)
			}
		}
		next.Jobs = jobs
	}
	return next.Normalize()
}

// validate rejects configurations that would fail at the endpoint, so the
// operator learns about the problem on save rather than from a silent
// fallback nobody notices.
func validate(cfg Config) error {
	cfg = cfg.Normalize()
	if cfg.Provider != ProviderOllama && cfg.Provider != ProviderOpenAICompatible {
		return invalidConfig("provider %q is not one of %s, %s",
			cfg.Provider, ProviderOllama, ProviderOpenAICompatible)
	}
	if cfg.BaseURL == "" {
		return invalidConfig("a base URL is required")
	}
	parsed, err := url.Parse(cfg.BaseURL)
	if err != nil || parsed.Host == "" || (parsed.Scheme != "http" && parsed.Scheme != "https") {
		return invalidConfig("the base URL must be an absolute http(s) URL")
	}
	if cfg.Model == "" {
		return invalidConfig("a model name is required")
	}
	if cfg.Enabled && !cfg.Configured() {
		return invalidConfig("set a base URL and a model before switching the auxiliary model on")
	}
	return nil
}

func invalidConfig(format string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrInvalidConfig, fmt.Sprintf(format, args...))
}

// ChatCompletionsURL is the endpoint an OpenAI-compatible provider is posted
// to. Operators paste both `https://api.example.com` and
// `https://api.example.com/v1`, so a base that already ends in /v1 is not
// given a second one.
func ChatCompletionsURL(baseURL string) string {
	base := strings.TrimRight(strings.TrimSpace(baseURL), "/")
	if strings.HasSuffix(base, "/v1") {
		return base + "/chat/completions"
	}
	return base + "/v1/chat/completions"
}

// OllamaChatURL is the endpoint Ollama is posted to, forgiving a base that
// already carries the /api segment for the same reason.
func OllamaChatURL(baseURL string) string {
	base := strings.TrimRight(strings.TrimSpace(baseURL), "/")
	if strings.HasSuffix(base, "/api") {
		return base + "/chat"
	}
	return base + "/api/chat"
}
